# Generated by Django 5.0.2 on 2024-03-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_corp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_private',
        ),
        migrations.AddField(
            model_name='user',
            name='userType',
            field=models.IntegerField(default=0),
        ),
    ]