# Generated by Django 5.0.2 on 2024-03-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_privateuser_user_rename_city_user_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='website_products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('Product_type', models.BooleanField(default=False)),
                ('value', models.PositiveIntegerField()),
                ('bin_type', models.CharField(max_length=255)),
            ],
        ),
    ]