# Generated by Django 5.0.2 on 2024-03-08 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_delete_privateuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='city',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='user',
            name='userType',
        ),
    ]
