# Generated by Django 5.0.2 on 2024-04-02 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_products_id_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='mapsForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='quizForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('option1', models.CharField(max_length=100)),
                ('option2', models.CharField(max_length=100)),
                ('option3', models.CharField(max_length=100)),
                ('option4', models.CharField(max_length=100)),
                ('correct_answer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ShopForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_type', models.BooleanField(default=True)),
                ('value', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='bin_type',
            field=models.CharField(blank=True, choices=[('כתום', 'כתום'), ('כחול', 'כחול'), ('חום', 'חום'), ('ירוק', 'ירוק'), ('סגול', 'סגול'), ('אפור', 'אפור'), ('מיחזורית- בקבוקי שתייה בנפח של מעל 1.5 ליטר ', 'מיחזורית- בקבוקי שתייה בנפח של מעל 1.5 ליטר '), ('קרטוניה', 'קרטוניה')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='products',
            name='value',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='usersContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDT', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='usersrecycling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDT', models.DateTimeField(auto_now_add=True)),
                ('userImg', models.ImageField(upload_to='usersImgs/')),
                ('status', models.IntegerField(choices=[(0, 'ממתין לאישור'), (1, 'אושר'), (2, 'נדחה')], default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
