# Generated by Django 5.0.3 on 2024-03-21 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_userscontacts_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='usersrecycling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDT', models.DateTimeField(auto_now_add=True)),
                ('userImg', models.ImageField(upload_to='usersImgs/')),
                ('status', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
