# Generated by Django 5.0.3 on 2024-03-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_mapsform_quizform_shopform_user_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersrecycling',
            name='status',
            field=models.IntegerField(choices=[(0, 'ממתין לאישור'), (1, 'אושר'), (2, 'נדחה')], default=0),
        ),
    ]
