# Generated by Django 5.0.3 on 2024-03-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_alter_usersrecycling_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='productImg',
            field=models.ImageField(blank=True, null=True, upload_to='storeImgs/'),
        ),
    ]
